### ISSUE TITLE
Your json files

### ISSUE THREAD

**Issue by Ugdhar** [staycrackin/Players-Workshop#1]
Took a peek into that zip file, and part of your problem is likely that your blockstate files are missing the .json extension on them, so they are probably not being found.

There should have been a FileNotFound Exception in your debug.log when trying to run your mod, saying it could not find the blockstate file.

**Comment by staycrackin** [comment]
Tried fixing the file extension to no avail. The problem still persists. I will be taking the time now to upload all of my code and then send another commit

**Comment by staycrackin** [comment]
YOU ARE AN AMAZING HUMAN BEING! Thank you so much for pointing that out to me I got it all fixed now.
